### ISSUE TITLE
Freeplane 1.8.x compatibility issue - can't start: unable to resolve class org.freeplane.features.icon.factory.MindIconFactory

### ISSUE THREAD

**Issue by OlafHaag** [gpapp/FreePlaneGTD#111]
Hi I just installed the add-on, created a new mindmap from template with _GTD_template.mm_, then got an error. It does prevent the add-on from working.

```
STDOUT: Apr. 19, 2020 10:05:45 PM org.freeplane.core.util.LogUtils info
INFORMATION: freeplane_version = 1.8.2; freeplane_xml_version = freeplane 1.8.0
git revision = fe91b62074ec1a8cb8ea6b74c411c7df2294b1ec Dimitry Polivaev 2020-04-12T09:10:31Z
java_version = 14; os_name = Windows 10; os_version = 10.0
STDOUT: Apr. 19, 2020 10:05:48 PM org.freeplane.core.util.LogUtils info
INFORMATION: added parsing support for standard date format dd.MM.yy
STDOUT: Apr. 19, 2020 10:05:48 PM org.freeplane.core.util.LogUtils info
INFORMATION: added parsing support for standard date time format dd.MM.yy, HH:mm
STDOUT: Apr. 19, 2020 10:05:48 PM org.freeplane.core.util.LogUtils info
INFORMATION: available locales not found
STDOUT: Apr. 19, 2020 10:05:48 PM org.freeplane.core.util.LogUtils info
INFORMATION: available locales not found
STDOUT: Apr. 19, 2020 10:05:58 PM org.freeplane.core.util.LogUtils info
INFORMATION: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: Apr. 19, 2020 10:05:58 PM org.freeplane.core.util.LogUtils info
INFORMATION: extending script's classpath by [C:\Users\me\AppData\Roaming\Freeplane\1.8.x\compiledscripts, C:\Users\me\AppData\Roaming\Freeplane\1.8.x\lib]
STDOUT: Apr. 19, 2020 10:05:58 PM org.freeplane.core.util.LogUtils info
INFORMATION: Loaded properties from bundle://7:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Apr. 19, 2020 10:06:14 PM org.freeplane.core.util.LogUtils severe
SCHWERWIEGEND: error compiling in C:\Users\me\AppData\Roaming\Freeplane\1.8.x\lib[ActionEditor.groovy, MultinodeActionEditor.groovy, GTDMapReader.groovy, GtdReportController.groovy, GtdReportViewController.groovy, GTDMapChangeListener.groovy, GTDMapSelectionListener.groovy, GTDNodeChangeListener.groovy, ArchiveTask.groovy, DoneMover.groovy, ReviewTask.groovy, ReportModel.groovy, ClipBoardUtil.groovy, DateUtil.groovy, Tag.groovy]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
C:\Users\me\AppData\Roaming\Freeplane\1.8.x\lib\freeplaneGTD\editor\ActionEditor.groovy: 10: unable to resolve class org.freeplane.features.icon.factory.MindIconFactory
 @ line 10, column 1.
   import org.freeplane.features.icon.factory.MindIconFactory
   ^

C:\Users\me\AppData\Roaming\Freeplane\1.8.x\lib\freeplaneGTD\GtdReportViewController.groovy: 13: unable to resolve class org.freeplane.features.icon.factory.MindIconFactory
 @ line 13, column 1.
   import org.freeplane.features.icon.factory.MindIconFactory
   ^

2 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:287)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:893)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:606)
	at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:316)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:111)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:90)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsInDirectory(ScriptCompiler.java:74)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsOnPath(ScriptCompiler.java:59)
	at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:175)
	at org.freeplane.plugin.script.ScriptingRegistration.<init>(ScriptingRegistration.java:142)
	at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:26)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:280)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:296)
	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:215)
	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:109)
	at org.freeplane.main.osgi.Activator.start(Activator.java:35)
	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:386)
	at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)
STDOUT: Apr. 19, 2020 10:06:15 PM org.freeplane.core.util.LogUtils info
INFORMATION: Loaded properties from bundle://7:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Apr. 19, 2020 10:06:15 PM org.freeplane.core.util.LogUtils info
INFORMATION: skipping deactivated newActivity.groovy(ON_SINGLE_NODE/addons.newActivity/main_menu_scripting/studyPlanner)
STDOUT: Apr. 19, 2020 10:06:15 PM org.freeplane.core.util.LogUtils info
INFORMATION: skipping deactivated countdownActivity.groovy(ON_SINGLE_NODE/addons.countdownActivity/main_menu_scripting/studyPlanner)
STDOUT: Apr. 19, 2020 10:06:15 PM org.freeplane.core.util.LogUtils info
INFORMATION: skipping deactivated activitiesList.groovy(ON_SINGLE_NODE/addons.activitiesList/main_menu_scripting/studyPlanner)
STDOUT: Apr. 19, 2020 10:06:15 PM org.freeplane.core.util.LogUtils info
INFORMATION: skipping deactivated help.groovy(ON_SINGLE_NODE/addons.help/main_menu_scripting/studyPlanner)
STDOUT: Apr. 19, 2020 10:06:15 PM org.freeplane.core.util.LogUtils info
INFORMATION: looking for scripts with the following endings: [groovy, js]
STDOUT: Framework launched
STDOUT: Apr. 19, 2020 10:06:16 PM org.freeplane.core.util.LogUtils info
INFORMATION: requesting mode: MindMap
STDOUT: Apr. 19, 2020 10:06:19 PM org.freeplane.core.util.LogUtils info
INFORMATION: running init script C:\Users\me\AppData\Roaming\Freeplane\1.8.x\scripts\init\AddGTDChangeListener.groovy
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: org.freeplane.plugin.script.ExecuteScriptException: BUG! exception in phase 'semantic analysis' in source unit 'C:\Users\me\AppData\Roaming\Freeplane\1.8.x\scripts\init\AddGTDChangeListener.groovy' The lookup for freeplaneGTD.GtdReportController caused a failed compilation. There should not have been any compilation from this call.
STDERR: at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:139)
STDERR: at org.freeplane.plugin.script.ScriptRunner.execute(ScriptRunner.java:56)
STDERR: at org.freeplane.plugin.script.ScriptingRegistration$6.onStartupFinished(ScriptingRegistration.java:280)
STDERR: at org.freeplane.features.mode.Controller.fireStartupFinished(Controller.java:327)
STDERR: at org.freeplane.main.application.FreeplaneGUIStarter.fireStartupFinished(FreeplaneGUIStarter.java:301)
STDERR: at org.freeplane.main.application.FreeplaneGUIStarter.access$500(FreeplaneGUIStarter.java:87)
STDERR: at org.freeplane.main.application.FreeplaneGUIStarter$3$2.run(FreeplaneGUIStarter.java:282)
STDERR: at org.freeplane.core.ui.components.UITools$5.lambda$focusGained$0(UITools.java:758)
STDERR: at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
STDERR: at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
STDERR: Caused by: BUG! exception in phase 'semantic analysis' in source unit 'C:\Users\me\AppData\Roaming\Freeplane\1.8.x\scripts\init\AddGTDChangeListener.groovy' The lookup for freeplaneGTD.GtdReportController caused a failed compilation. There should not have been any compilation from this call.
STDERR: at org.codehaus.groovy.control.ClassNodeResolver.findByClassLoading(ClassNodeResolver.java:214)
STDERR: at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:198)
STDERR: at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
STDERR: at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
STDERR: at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:869)
STDERR: at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:498)
STDERR: at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1430)
STDERR: at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:261)
STDERR: at org.codehaus.groovy.control.CompilationUnit.lambda$new$16(CompilationUnit.java:717)
STDERR: at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)
STDERR: at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)
STDERR: at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
STDERR: at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
STDERR: at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
STDERR: at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
STDERR: at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
STDERR: at org.freeplane.plugin.script.GroovyShell.parseClass(GroovyShell.java:104)
STDERR: at org.freeplane.plugin.script.GroovyShell.parse(GroovyShell.java:116)
STDERR: at org.freeplane.plugin.script.GroovyShell.parse(GroovyShell.java:125)
STDERR: at org.freeplane.plugin.script.GroovyScript.compileAndCache(GroovyScript.java:190)
STDERR: at org.freeplane.plugin.script.GroovyScript.access$200(GroovyScript.java:50)
STDERR: at org.freeplane.plugin.script.GroovyScript$3.run(GroovyScript.java:155)
STDERR: at org.freeplane.plugin.script.GroovyScript$3.run(GroovyScript.java:149)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at org.freeplane.plugin.script.GroovyScript.trustedCompileAndCache(GroovyScript.java:149)
STDERR: at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:107)
STDERR: ... 22 more
STDERR: Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/C:/Users/me/AppData/Roaming/Freeplane/1.8.x/lib/freeplaneGTD/GtdReportViewController.groovy: 13: unable to resolve class org.freeplane.features.icon.factory.MindIconFactory
 @ line 13, column 1.
   import org.freeplane.features.icon.factory.MindIconFactory
   ^

1 error
STDERR: at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:287)
STDERR: at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:893)
STDERR: at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)
STDERR: at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
STDERR: at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
STDERR: at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
STDERR: at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
STDERR: at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
STDERR: at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
STDERR: at groovy.lang.GroovyClassLoader.recompile(GroovyClassLoader.java:954)
STDERR: at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:910)
STDERR: at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:979)
STDERR: at org.freeplane.plugin.script.ScriptClassLoader.superLoadClass(ScriptClassLoader.java:102)
STDERR: at org.freeplane.plugin.script.ScriptClassLoader.access$200(ScriptClassLoader.java:20)
STDERR: at org.freeplane.plugin.script.ScriptClassLoader$3.run(ScriptClassLoader.java:92)
STDERR: at org.freeplane.plugin.script.ScriptClassLoader$3.run(ScriptClassLoader.java:89)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at org.freeplane.plugin.script.ScriptClassLoader.loadClass(ScriptClassLoader.java:89)
STDERR: at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
STDERR: at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:869)
STDERR: at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:745)
STDERR: at org.codehaus.groovy.control.ClassNodeResolver.findByClassLoading(ClassNodeResolver.java:209)
STDERR: ... 47 more
```

Hitting alt+H gives me:
```STDOUT: Apr. 19, 2020 10:12:51 PM org.freeplane.core.util.LogUtils warn
WARNUNG: ExecuteScriptAction failed:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/C:/Users/me/AppData/Roaming/Freeplane/1.8.x/lib/freeplaneGTD/GtdReportViewController.groovy: 13: unable to resolve class org.freeplane.features.icon.factory.MindIconFactory
 @ line 13, column 1.
   import org.freeplane.features.icon.factory.MindIconFactory
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:287)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:893)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.recompile(GroovyClassLoader.java:954)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:910)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:979)
	at org.freeplane.plugin.script.ScriptClassLoader.superLoadClass(ScriptClassLoader.java:102)
	at org.freeplane.plugin.script.ScriptClassLoader.access$200(ScriptClassLoader.java:20)
	at org.freeplane.plugin.script.ScriptClassLoader$3.run(ScriptClassLoader.java:92)
	at org.freeplane.plugin.script.ScriptClassLoader$3.run(ScriptClassLoader.java:89)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.freeplane.plugin.script.ScriptClassLoader.loadClass(ScriptClassLoader.java:89)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:869)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:745)
	at org.codehaus.groovy.control.ClassNodeResolver.findByClassLoading(ClassNodeResolver.java:209)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:198)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
	at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:869)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:498)
	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1430)
	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:261)
	at org.codehaus.groovy.control.CompilationUnit.lambda$new$16(CompilationUnit.java:717)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at org.freeplane.plugin.script.GroovyShell.parseClass(GroovyShell.java:104)
	at org.freeplane.plugin.script.GroovyShell.parse(GroovyShell.java:116)
	at org.freeplane.plugin.script.GroovyShell.parse(GroovyShell.java:125)
	at org.freeplane.plugin.script.GroovyScript.compileAndCache(GroovyScript.java:190)
	at org.freeplane.plugin.script.GroovyScript.access$200(GroovyScript.java:50)
	at org.freeplane.plugin.script.GroovyScript$3.run(GroovyScript.java:155)
	at org.freeplane.plugin.script.GroovyScript$3.run(GroovyScript.java:149)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.freeplane.plugin.script.GroovyScript.trustedCompileAndCache(GroovyScript.java:149)
	at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:107)
	at org.freeplane.plugin.script.ScriptRunner.execute(ScriptRunner.java:56)
	at org.freeplane.plugin.script.ExecuteScriptAction.actionPerformed(ExecuteScriptAction.java:93)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at org.freeplane.core.ui.ActionAcceleratorManager.processKeyBinding(ActionAcceleratorManager.java:443)
	at org.freeplane.main.mindmapmode.MModeControllerFactory$2.processKeyBinding(MModeControllerFactory.java:288)
	at org.freeplane.view.swing.ui.UserInputListenerFactory$2.processKeyBinding(UserInputListenerFactory.java:172)
	at org.freeplane.core.ui.components.FreeplaneMenuBar.processKeyBinding(FreeplaneMenuBar.java:99)
	at org.freeplane.main.application.MenuKeyProcessor.processKeyBinding(MenuKeyProcessor.java:26)
	at org.freeplane.main.application.ConnectedToMenuView.processKeyBinding(ConnectedToMenuView.java:41)
	at java.desktop/javax.swing.JComponent.processKeyBindings(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
STDOUT: Apr. 19, 2020 10:12:51 PM org.freeplane.core.util.LogUtils warn
WARNUNG: error executing script C:\Users\me\AppData\Roaming\Freeplane\1.8.x\addons\freeplaneGTD\scripts\ParseShorthand.groovy - giving up
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/C:/Users/me/AppData/Roaming/Freeplane/1.8.x/lib/freeplaneGTD/GtdReportViewController.groovy: 13: unable to resolve class org.freeplane.features.icon.factory.MindIconFactory
 @ line 13, column 1.
   import org.freeplane.features.icon.factory.MindIconFactory
   ^

1 error
STDOUT: Apr. 19, 2020 10:12:51 PM org.freeplane.core.util.LogUtils warn
WARNUNG: Fehler beim Ausführen des Skripts:
BUG! exception in phase 'semantic analysis' in source unit
    'C:\Users\me\AppData\Roaming\Freeplane\1.8.x\addons\freeplaneGTD\scripts\ParseShorthand.groovy'
    The lookup for freeplaneGTD.GtdReportController caused a failed compilation.
    There should not have been any compilation from this call.
STDOUT: Apr. 19, 2020 10:13:01 PM org.freeplane.core.util.LogUtils info
INFORMATION: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/Users/me/AppData/Roaming/Freeplane/1.8.x/logs/]
```

**Comment by gpapp** [comment]
It seems that there was a major refactor of icons between 1.7.x and 1.8.x version of Freeplane. This needs some overhaul to work.

**Comment by proudeng** [comment]
just checked that following java class was removed in Freeplane 1.8.0:
"freeplane/src/main/java/org/freeplane/features/icon/factory/MindIconFactory.java"

**Comment by gpapp** [comment]
Fixed issues from Freeplane upstream refactor and package updates.
