### ISSUE TITLE
GTDNodeChangeListener crashes when script updates stylenodes

### ISSUE THREAD

**Issue by EdoFro** [gpapp/FreePlaneGTD#125]
Hi @gpapp,
For my add-ons I created a library to copy the styles and their conditional style rules from a template map to the user mindmap. It also copy the icons and sttributes if the style node has them.

I installed FreeplaneGTD and used my script to import styles and it throwed an error:

![image](https://user-images.githubusercontent.com/35700575/221384443-9aceddd8-4e1b-4e88-9e4f-273d85a1b197.png)

the method mentioned in the log is [UserStyles.copyIcons](https://github.com/EdoFro/Freeplane_Pseudo-Freeplane-API/blob/d7748d3b5c765639c8c6acb1beb93eaba8b6c878/pseudoFreeplaneAPI/src/main/groovy/UserStyles.groovy#L93),  that, in this case, copies the icons from a styleNode in one map to a styleNode in another map.

the error refers to [this line in GTDNodeChangeListener](https://github.com/gpapp/FreePlaneGTD/blob/45e325d7fa42127ae742b0de7cdfb3b0d3e24e5a/src/zips/lib/freeplaneGTD/listener/GTDNodeChangeListener.groovy#L102)

I think it may be a problem with the stylenodes and how they report their changes.

Can you please see if it is a GTDNodeChangeListener bug or tell me what should I change to overcome this error?

thanks,

edo
 

PD: here is the full stacktrace:
```
SEVERE: Error caught:Cannot get property 'attributes' on null object
java.lang.NullPointerException: Cannot get property 'attributes' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:62)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at freeplaneGTD.listener.GTDNodeChangeListener.nodeChanged(GTDNodeChangeListener.groovy:102)
	at org.freeplane.features.map.NodeModel.fireSingleNodeChanged(NodeModel.java:222)
	at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:216)
	at org.freeplane.features.map.MapController.fireNodeChanged(MapController.java:664)
	at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:943)
	at org.freeplane.features.map.MapController.nodeChanged(MapController.java:887)
	at org.freeplane.features.icon.mindmapmode.MIconController$3.act(MIconController.java:288)
	at org.freeplane.features.mode.mindmapmode.MModeController.lambda$execute$0(MModeController.java:187)
	at org.freeplane.features.ui.FrameController$StaticInvoker.invokeAndWait(FrameController.java:936)
	at org.freeplane.features.ui.FrameController$StaticInvoker.access$500(FrameController.java:933)
	at org.freeplane.features.ui.FrameController.invokeAndWait(FrameController.java:930)
	at org.freeplane.features.mode.mindmapmode.MModeController.execute(MModeController.java:185)
	at org.freeplane.features.icon.mindmapmode.MIconController.addIcon(MIconController.java:302)
	at org.freeplane.plugin.script.proxy.IconsProxy.add(IconsProxy.java:29)
	at org.freeplane.plugin.script.proxy.IconsProxy.addAll(IconsProxy.java:35)
	at org.freeplane.api.Icons$addAll$0.call(Unknown Source)
	at edofro.pseudofreeplaneapi.UserStyles.copyIcons(UserStyles.groovy:93)
	at edofro.pseudofreeplaneapi.UserStyles.copyIcons(UserStyles.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:342)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:63)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at edofro.pseudofreeplaneapi.UserStyles$_copyUserStyles_closure1.doCall(UserStyles.groovy:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2386)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2371)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2412)
	at org.codehaus.groovy.runtime.dgm$203.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:253)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at edofro.pseudofreeplaneapi.UserStyles.copyUserStyles(UserStyles.groovy:30)
	at edofro.pseudofreeplaneapi.UserStyles$copyUserStyles.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at edofro.pseudofreeplaneapi.UserStyles.copyUserStyles(UserStyles.groovy:46)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at importMDIStyles.run(importMDIStyles.groovy:14)
	at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:114)
	at org.freeplane.plugin.script.ScriptRunner.execute(ScriptRunner.java:56)
	at org.freeplane.plugin.script.ExecuteScriptAction.actionPerformed(ExecuteScriptAction.java:112)
	at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:93)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by gpapp** [comment]
My addon is doing things, that the addon system was not built to handle. It's created to be used as-is. There is no guarantee it would play nice with other addons or user scripts. (Also it cannot be deactivated once installed, to get rid of it it needs to be removed!) 

The FreePlaneGTD addon assumes to be run on nodes of the active map. It looks up the node modified by its createdID property. Your scripts modify nodes, that are not in the active map, and thus are not found.
This will be an issue for all addons that hook on the listener. But I don't think anyone else was foolish enough to go this deep with an addon. 

It could be prevented by either 
- deactivating listeners before copy in your scropts. Mine has a set enabled method for this
- ignoring the off-the-map nodes in mine 
Both resulting in loosing the changes the scripts do in another map. 

The proper way to handle it would be looking up the node in the other map or changing the active map in the listener. Since I'm using ScriptUtils to look up the map that would require digging into the bowels of the fp application, to see what makes it tick, that I will not do ever again. 

I'll add a fix, but will not release a new version just for this. You are already in the addon folder, patch it there. May bring similar issues to the light though.

**Comment by EdoFro** [comment]
Hi @gpapp,
Thanks for the information.


> My addon is doing things, that the addon system was not built to handle. It's created to be used as-is. There is no guarantee it would play nice with other addons or user scripts.

I understand this. I really don't use this add-on. @bepolymathe uses both (my add-on and this) and he has experienced these errors. I wanted to know if there was an easy way to solve this.


-----
> It could be prevented by either
> 
> * deactivating listeners before copy in your scropts. Mine has a set enabled method for this

I was making some test scripts to explore this idea and got to this one. Do you think it may help?
```groovy
def extraListeners = node.mindMap
                        .modeController.mapController.nodeChangeListeners
                        .findAll{!it.class.name.startsWith('org.freeplane.') && it.properties.containsKey('enabled')}

def extraListenersInitialState = [] + extraListeners*.enabled

extraListeners*.enabled = false

// do my stuff

extraListeners.eachWithIndex{ l, i ->
   l.enabled = extraListenersInitialState[i]
}

```

Another question:
Why don't you use the API method ( org.freeplane.api.MindMap.addListeners() )?



----
> (Also it cannot be deactivated once installed, to get rid of it it needs to be removed!)

Maybe you can add this to your init script to execute it only if the add-on is active:
```groovy
import org.freeplane.main.addons.AddOnsController

def isActive = AddOnsController.getController().getInstalledAddOns().find{it.name == 'freeplaneGTD'}?.active

if (isActive){
    // do your stuff, activate listeners, etc
}
else {
    // do nothing
}
```

----

Best regards,

edo

**Comment by EdoFro** [comment]
> The FreePlaneGTD addon assumes to be run on nodes of the active map. It looks up the node modified by its createdID property. Your scripts modify nodes, that are not in the active map, and thus are not found.

I think this may not be the problem. I just notice that some of the styleNodes have no **Id**

Here is the event properties of the GTDNodeChangeListener when the error happens:
```
[source:baseFolder, id:0, 
COMPONENT_EVENT_MASK:1, CONTAINER_EVENT_MASK:2, FOCUS_EVENT_MASK:4, KEY_EVENT_MASK:8, 
MOUSE_EVENT_MASK:16, MOUSE_MOTION_EVENT_MASK:32, WINDOW_EVENT_MASK:64, ACTION_EVENT_MASK:128, 
ADJUSTMENT_EVENT_MASK:256, ITEM_EVENT_MASK:512, TEXT_EVENT_MASK:1024, INPUT_METHOD_EVENT_MASK:2048, 
PAINT_EVENT_MASK:8192, INVOCATION_EVENT_MASK:16384, HIERARCHY_EVENT_MASK:32768, 
HIERARCHY_BOUNDS_EVENT_MASK:65536, MOUSE_WHEEL_EVENT_MASK:131072, WINDOW_STATE_EVENT_MASK:262144, 
WINDOW_FOCUS_EVENT_MASK:524288, RESERVED_ID_MAX:1999, 
newValue:null, oldValue:emoji-1F4BD, property:icon, ID:0, class:class org.freeplane.features.map.NodeChangeEvent, 
node:baseFolder]
```

there you can see that `id=0` and `ID=0`

Here is an imge of the XML of the mindMap. There you can see that the selected styleNode has no ID yet.
![image](https://user-images.githubusercontent.com/35700575/221423083-603f84c4-5556-4df6-a377-817ecca66ff2.png)

I think that maybe styleNodes get an ID when they are modified and not when they are created or something like that.

Maybe the solution is simplier. Maybe you just have to add a line of code to check if the node has an ID different than 0 and that's all.

Best regards,

edo

**Comment by bepolymathe** [comment]
Thank you for your efforts!
