### ISSUE TITLE
backwards compatibility to use AddOn with FP v1.2.x

### ISSUE THREAD

**Issue by nnako** [gpapp/FreePlaneGTD#32]
Currently, the installation process for this AddOn is interrupted by an Error when trying to run it with Freeplane v1.2.x (I've tried v1.2.20). An error message saying ***"No signature of method: org.freeplane.plugin.script.proxy.Proxy$NodeRO.expandVariables() is applicable for argument types: (org.freeplane.features.format.FormattedNumber) values: [2]"*** will be displayed.

**Would it be possible to pimp the AddOn so that it could be installed on older Freeplane versions like v1.2.x?**

See the LOG file (could not attach it as a file, as only pictures seem possible):

```
08.09.2015 10:09:39 org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.2.20; freeplane_xml_version = freeplane 1.2.0
git revision = 4b28962_dpolivaev_2012-10-182136570200
java_version = 1.6.0_33; os_name = Windows 7; os_version = 6.1
08.09.2015 10:09:40 org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format EEEE, d. MMMM yyyy
08.09.2015 10:09:40 org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format dd.MM.yy HH:mm

STDOUT: Loaded properties from bundle://3.0:0/org/freeplane/plugin/formula/defaults.properties
STDOUT: Loaded properties from bundle://5.0:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Framework launched08.09.2015 10:09:41 org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
08.09.2015 10:10:04 org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
INFO: installing add-on from I:\Documents\_DROPBOX\mindmaps\_addons\PAPP__G.__2015_._freeplaneGTD-v1.4.addon.mm

STDOUT: properties: [name:freeplaneGTD, version:v1.4, author:Gergely Papp, freeplaneVersionFrom:1.2.10, downloadUrl:http://www.itworks.hu/freeplanegtd-release/, changelogUrl:http://www.itworks.hu/freeplanegtd-release/, title:Freeplane|GTD+, homepage:http://www.itworks.hu/index.php/freeplane-gtd]
STDOUT: description: <html>
  <head>
    
  </head>
  <body>
    <p>
      Freeplane|GTD creates views of GTD-style Next Action lists extracted from a mind map, providing views:
    </p>
    <ul>
      <li>
        By Project
      </li>
      <li>
        By Context (where the next action gets done)
      </li>
      <li>
        By Owner (who owns it, if not you)
      </li>
      <li>
        By Due Date (when)
      </li>
    </ul>
    <p>
      The completed actions can be marked and filtered.
    </p>
    <p>
      
    </p>
    <p>
      Markers (icons) can be configured to correspond to contexts
    </p>
    <p>
      
    </p>
    <p>
      Simple action editor is provided.
    </p>
  </body>
</html>
STDOUT: license: This add-on is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
STDOUT: translations: [en:[main_menu_scripting/freeplaneGTD:FreeplaneGTD, addons.freeplaneGTD:FreeplaneGTD, addons.freeplaneGTD.listActions:Next action list, addons.freeplaneGTD.parseShorthand:Convert tasks from shorthand, addons.freeplaneGTD.editAction:Edit action, OptionPanel.separator.freeplaneGTD:freeplaneGTD addon, OptionPanel.freeplaneGTD_filter_done:Filter completed tasks by default, OptionPanel.freeplaneGTD_default_view:Default action view, freeplaneGTD_view_project:Project, freeplaneGTD_view_who:Who, freeplaneGTD_view_context:Context, freeplaneGTD_view_when:Timeline, freeplaneGTD.tab.project.title:By Project, freeplaneGTD.tab.project.tooltip:List actions by project, freeplaneGTD.tab.who.title:By Who, freeplaneGTD.tab.who.tooltip:List action by delegates, freeplaneGTD.tab.context.title:By Context, freeplaneGTD.tab.context.tooltip:List actions by context, freeplaneGTD.tab.when.title:Timeline, freeplaneGTD.tab.when.tooltip:List actions by time, freeplaneGTD.tab.about.title:About, freeplaneGTD.tab.about.tooltip:About Freeplane|GTD+, freeplaneGTD.button.refresh:Refresh, freeplaneGTD.button.print:Print, freeplaneGTD.button.copy:Copy, freeplaneGTD.button.cancel:Close, freeplaneGTD.button.filter_done:Filter done, freeplaneGTD.button.show_notes:Display notes, freeplaneGTD.button.done:Done, freeplaneGTD.button.select:Select nodes, freeplaneGTD.view.context.unassigned:Unassigned, freeplaneGTD.view.when.today:Today, freeplaneGTD.view.when.this_week:This week, freeplaneGTD.actioneditor.title:Edit action, freeplaneGTD.actioneditor.action:Action, freeplaneGTD.actioneditor.delegate:Who, freeplaneGTD.actioneditor.context:Context, freeplaneGTD.actioneditor.when:When, freeplaneGTD.actioneditor.today:Today, freeplaneGTD.actioneditor.priority:Priority, freeplaneGTD.actioneditor.done:Done, freeplaneGTD.message.copy_ok:Selection copied to clipboard.], hu:[addons.freeplaneGTD:FreeplaneGTD, addons.freeplaneGTD.listActions:Teend\u0151k, addons.freeplaneGTD.parseShorthand:Feladatok l\u00E9trehoz\u00E1sa r\u00F6vid\u00EDt\u00E9sb\u0151l, addons.freeplaneGTD.editAction:Szerkeszt\u00E9s, main_menu_scripting/freeplaneGTD:FreeplaneGTD, OptionPanel.separator.freeplaneGTD:freeplaneGTD tulajdons\u00E1gai, OptionPanel.freeplaneGTD_filter_done:K\u00E9sz elemek sz\u0171r\u00E9se alapb\u00F3l, OptionPanel.freeplaneGTD_default_view:Kezdeti feladat n\u00E9zet, freeplaneGTD_view_project:Projekt, freeplaneGTD_view_who:Ki, freeplaneGTD_view_context:Kontextus, freeplaneGTD_view_when:Id\u0151vonal, freeplaneGTD.tab.project.title:Projektenk\u00E9nt, freeplaneGTD.tab.project.tooltip:Feladatok list\u00E1ja projektenk\u00E9nt, freeplaneGTD.tab.who.title:Szem\u00E9lyenk\u00E9nt, freeplaneGTD.tab.who.tooltip:Feladatok list\u00E1ja szem\u00E9lyenk\u00E9nt, freeplaneGTD.tab.context.title:Kontextusonk\u00E9nt, freeplaneGTD.tab.when.title:Id\u0151vonal, freeplaneGTD.tab.when.tooltip:Feladatok list\u00E1ja id\u0151rendi sorrendben, freeplaneGTD.tab.about.title:N\u00E9vjegy, freeplaneGTD.tab.about.tooltip:A Freeplane|GTD+ n\u00E9vjegye, freeplaneGTD.button.refresh:Friss\u00EDt\u00E9s, freeplaneGTD.button.print:Nyomtat\u00E1s, freeplaneGTD.button.copy:V\u00E1g\u00F3lapra, freeplaneGTD.button.cancel:Bez\u00E1r\u00E1s, freeplaneGTD.button.filter_done:Lez\u00E1rtak sz\u0171r\u00E9se, freeplaneGTD.button.show_notes:Jegyzetek megjelen\u00EDt\u00E9se, freeplaneGTD.button.done:Ok, freeplaneGTD.button.select:Elemek kiv\u00E1laszt\u00E1sa, freeplaneGTD.view.context.unassigned:Kontextus n\u00E9lk\u00FCl, freeplaneGTD.view.when.today:Ma, freeplaneGTD.view.when.this_week:Ezen a h\u00E9ten, freeplaneGTD.actioneditor.title:Feladat szerkeszt\u00E9se, freeplaneGTD.actioneditor.action:Feladat, freeplaneGTD.actioneditor.delegate:V\u00E9grehajt\u00F3, freeplaneGTD.actioneditor.context:Kontextus, freeplaneGTD.actioneditor.when:Id\u0151pont, freeplaneGTD.actioneditor.today:Ma, freeplaneGTD.actioneditor.priority:Priorit\u00E1s, freeplaneGTD.actioneditor.done:K\u00E9sz, freeplaneGTD.message.copy_ok:V\u00E1lasztott elemek a v\u00E1g\u00F3lapra m\u00E1solva.]]
STDOUT: preferences.xml: <?xml version="1.0" encoding="UTF-8"?>
<preferences_structure>
         <tabbed_pane>
                  <tab name="plugins">
                           <separator name="freeplaneGTD">
                <boolean name="freeplaneGTD_filter_done" min="0" />
                <combo name="freeplaneGTD_default_view">
                    <choice value="0" text="freeplaneGTD_view_project" />
                    <choice value="1" text="freeplaneGTD_view_who" />
                    <choice value="2" text="freeplaneGTD_view_context" />
                    <choice value="3" text="freeplaneGTD_view_when" />
                </combo>
                           </separator>
                  </tab>
         </tabbed_pane>
</preferences_structure>08.09.2015 10:12:38 org.freeplane.core.util.LogUtils warn
WARNUNG: installation failure
groovy.lang.MissingMethodException: No signature of method: org.freeplane.plugin.script.proxy.Proxy$NodeRO.expandVariables() is applicable for argument types: (org.freeplane.features.format.FormattedNumber) values: [2]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:78)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at Script1$_parseDefaultProperties_closure4.doCall(Script1.groovy:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:877)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.inject(DefaultGroovyMethods.java:3673)
	at org.codehaus.groovy.runtime.dgm$400.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at Script1.parseDefaultProperties(Script1.groovy:171)
	at Script1$parseDefaultProperties.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at Script1.parse(Script1.groovy:442)
	at Script1.run(Script1.groovy:523)
	at org.freeplane.plugin.script.ScriptingEngine$2.evaluate(ScriptingEngine.java:157)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:618)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:589)
	at org.freeplane.plugin.script.ScriptingEngine.executeScript(ScriptingEngine.java:169)
	at org.freeplane.plugin.script.ScriptingEngine.executeScript(ScriptingEngine.java:79)
	at org.freeplane.plugin.script.ScriptingEngine.executeScript(ScriptingEngine.java:238)
	at org.freeplane.plugin.script.addons.AddOnInstallerPanel$1.actionPerformed(AddOnInstallerPanel.java:146)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.Dialog$1.run(Unknown Source)
	at java.awt.Dialog$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at org.freeplane.plugin.script.addons.ManageAddOnsAction.actionPerformed(ManageAddOnsAction.java:17)
	at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:177)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.awt.EventQueue$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
08.09.2015 10:12:45 org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/PROGS/FreeplanePortable/Data/Freeplane/1.2.x/]
```

**Comment by gpapp** [comment]
It would require reimplementing the changed API in the add-on itself.

**Comment by gpapp** [comment]
Marked add-on as incompatible with Freeplane versions before 1.3.10 :(
