### ISSUE TITLE
Java Security Exception on OS X (FreePlaneGTD version 2)

### ISSUE THREAD

**Issue by Pugio** [gpapp/FreePlaneGTD#78]
Just installed FreePlaneGTD on the latest Freeplane and got:

```
at 2018-01-28 15:27:55 CMT,  hash f127f30cf67a3265a3c2b9f64c7d1e66
previous report : no reports sent before
freeplane_version = 1.6.12; freeplane_xml_version = freeplane 1.6.0
git revision = 12084cd69afdbb18f674cb9c53862a42c2ada446 Dimitry Polivaev 2018-01-07T18:16:49Z
java_version = 1.8.0_121; os_name = Mac OS X; os_version = 10.11.6
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at org.freeplane.plugin.script.InternationalizedSecurityManager.checkPermission(InternationalizedSecurityManager.java:216)
	at java.lang.SecurityManager.checkAccess(SecurityManager.java:676)
	at java.lang.Thread.checkAccess(Thread.java:1387)
	at java.lang.Thread.setPriority(Thread.java:1084)
	at java.lang.Thread.init(Thread.java:414)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:596)
	at com.sun.webkit.WatchdogTimer$CustomThreadFactory.newThread(WatchdogTimer.java:118)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.sun.webkit.WatchdogTimer.fwkStart(WatchdogTimer.java:78)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$null$47(WebEngine.java:1226)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.lang.IllegalStateException
	at com.sun.webkit.WatchdogTimer.fwkStop(WatchdogTimer.java:84)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$null$47(WebEngine.java:1226)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at org.freeplane.plugin.script.InternationalizedSecurityManager.checkPermission(InternationalizedSecurityManager.java:216)
	at java.lang.SecurityManager.checkAccess(SecurityManager.java:676)
	at java.lang.Thread.checkAccess(Thread.java:1387)
	at java.lang.Thread.setPriority(Thread.java:1084)
	at java.lang.Thread.init(Thread.java:414)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:596)
	at com.sun.webkit.WatchdogTimer$CustomThreadFactory.newThread(WatchdogTimer.java:118)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.sun.webkit.WatchdogTimer.fwkStart(WatchdogTimer.java:78)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:859)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$101(URLLoader.java:850)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.lang.IllegalStateException
	at com.sun.webkit.WatchdogTimer.fwkStop(WatchdogTimer.java:84)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:859)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$101(URLLoader.java:850)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

This window pops up every time I activate the Next Action List, or click on any of the filter radio buttons.

**Comment by gpapp** [comment]
Now that's a weird bug. It started to occur on my client as well, while it seemed to work OK before. I thought it's because of my local modifications.

It happens within standard Java code, so it ought to be some issue within the Java Runtime threading itself.

I won't be able to fix it without finding the exact steps required to replicate it, than debug it to see how to work around it.

**Comment by dekatechi** [comment]
hello mr papp, thank you for your work on gtd+

i want to second Pugios report. exactly the same issue here, also on osx. every input in 'Next Actions' list prints error: 

freeplane_version = 1.6.12; freeplane_xml_version = freeplane 1.6.0
java_version = 1.8.0_121; osx 10.9.
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at org.freeplane.plugin.script.InternationalizedSecurityManager.checkPermission(InternationalizedSecurityManager.java:216)
	at java.lang.SecurityManager.checkAccess(SecurityManager.java:676)
	at java.lang.Thread.checkAccess(Thread.java:1387)
	at java.lang.Thread.setPriority(Thread.java:1084)
	at java.lang.Thread.init(Thread.java:414)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:596)
	at com.sun.webkit.WatchdogTimer$CustomThreadFactory.newThread(WatchdogTimer.java:118)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.sun.webkit.WatchdogTimer.fwkStart(WatchdogTimer.java:78)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$null$47(WebEngine.java:1226)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.lang.IllegalStateException
	at com.sun.webkit.WatchdogTimer.fwkStop(WatchdogTimer.java:84)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$null$47(WebEngine.java:1226)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at org.freeplane.plugin.script.InternationalizedSecurityManager.checkPermission(InternationalizedSecurityManager.java:216)
	at java.lang.SecurityManager.checkAccess(SecurityManager.java:676)
	at java.lang.Thread.checkAccess(Thread.java:1387)
	at java.lang.Thread.setPriority(Thread.java:1084)
	at java.lang.Thread.init(Thread.java:414)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:596)
	at com.sun.webkit.WatchdogTimer$CustomThreadFactory.newThread(WatchdogTimer.java:118)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.sun.webkit.WatchdogTimer.fwkStart(WatchdogTimer.java:78)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:859)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$101(URLLoader.java:850)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.lang.IllegalStateException
	at com.sun.webkit.WatchdogTimer.fwkStop(WatchdogTimer.java:84)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1482)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1003)
	at javafx.scene.web.WebEngine$executeScript$1.call(Unknown Source)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy:185)
	at freeplaneGTD.ReportWindow$1.changed(ReportWindow.groovy)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1285)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1396)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1278)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1265)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2443)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2287)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:859)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$101(URLLoader.java:850)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

The 'Next Actions' list is, anyway, working and displaying all nextactions and structure properly. 
Sideeffect on my machine: CPU is running hot when using the addon. @Pugio, is yours also running hot?

**Comment by gpapp** [comment]
I've tried to look into it. There seems to be an upstream bug, nested inside the scripting API of Freeplane itself. 

When I use the scripting interface to interact with the map, it seems to run the commands concurrently and those seem to step on each others toes. 

To reduce the issue impact you should turn off the automatic node folding in the addon's preferences. Folding/unfolding of nodes is implemented in a recursive way using the scripting proxy objects.

Even with these off, I see that the select and center node on screen commands sometimes hang.

I honestly have no idea to solve this. I have no way of checking when the proxy action is completed to queue the actions sequentially. Also it's now practically impossible to hack the freeplane directly anymore (I used to do that in earlier versions)

NB: Funny thing is it is unable to exit the program because of it's own security manager. So when it says it's exiting the program and leaves the add-on pane on, I can use the tasks to navigate back to the allegedly closed application.

**Comment by dekatechi** [comment]
Ok, sounds like there is no solution possible for this if not at least the freeplane guys would take a look at it.

Workaround: Click "Never send" when 'Automatic Error Report' window pops up the first time. Afterwards, using the plugin is working flawless. Of course the error notification count in the left bottom of freeplane window is accumulating with every click at plugin as a result.

**Comment by gpapp** [comment]
As an ugly hack I'll try to add some forced delays in between the commands, to try to reduce the effect. 

Given enough time I might just hack into the internals of the Freeplane, to deliver some brutal workaround, but  every time I've done that in the past, it stopped working on the next release. :(

**Comment by gpapp** [comment]
Turns out I was just reckless and assumed Java is able to interact between it's own internal threads. Simple solution fixes it. 
I'll release a new version sometime later, until then you can replace the JSHandler.groovy and restart the application to get rid of these annoying issues.

**Comment by gpapp** [comment]
You can get the latest release at http://www.itworks.hu/freeplanegtd-release/
