### ISSUE TITLE
FreePlaneGTD 2.0.1 causes automatic bug report when launching Freeplane 1.16.5

### ISSUE THREAD

**Issue by stuieordie** [gpapp/FreePlaneGTD#83]
When you try and run the Next Action script you get:
    Error executing the script: null

Contents of bug report window:
    at 2018-06-11 19:40:47 CMT,  hash 0e415c4cdf88dae38bf5bc5bf7043d68
previous report : no reports sent before
freeplane_version = 1.6.15; freeplane_xml_version = freeplane 1.6.0
git revision = fe0b3d3c7f05668d40ca1433346f5bec92e26743 Dimitry Polivaev 2018-05-13T15:41:44Z
java_version = 1.8.0_171; os_name = Linux; os_version = 4.13.0-43-generic
error compiling in /home/mstuart/.config/freeplane/1.6.x/lib[ArchiveTask.groovy, DoneMover.groovy, ReviewTask.groovy, ReportModel.groovy, JSHandler.groovy, DateUtil.groovy, Tag.groovy, ReportWindow.groovy, ClipBoardUtil.groovy, GTDMapReader.groovy, MultinodeActionEditor.groovy, ActionEditor.groovy]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 8: unable to resolve class javafx.embed.swing.JFXPanel
 @ line 8, column 1.
   import javafx.embed.swing.JFXPanel
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 4: unable to resolve class javafx.application.Platform
 @ line 4, column 1.
   import javafx.application.Platform
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 6: unable to resolve class javafx.beans.value.ObservableValue
 @ line 6, column 1.
   import javafx.beans.value.ObservableValue
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 12: unable to resolve class netscape.javascript.JSObject
 @ line 12, column 1.
   import netscape.javascript.JSObject
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 7: unable to resolve class javafx.concurrent.Worker
 @ line 7, column 1.
   import javafx.concurrent.Worker
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 5: unable to resolve class javafx.beans.value.ChangeListener
 @ line 5, column 1.
   import javafx.beans.value.ChangeListener
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 11: unable to resolve class javafx.scene.web.WebView
 @ line 11, column 1.
   import javafx.scene.web.WebView
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 9: unable to resolve class javafx.scene.Scene
 @ line 9, column 1.
   import javafx.scene.Scene
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 10: unable to resolve class javafx.scene.web.WebEngine
 @ line 10, column 1.
   import javafx.scene.web.WebEngine
   ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 181: unable to resolve class Worker.State 
 @ line 181, column 78.
   ddListener(new ChangeListener<Worker.Sta
                                 ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 183: unable to resolve class Worker.State 
 @ line 183, column 38.
   								void changed(ObservableValue<? extends Worker.State> observable, Worker.State oldValue, Worker.State newValue) {
                                        ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 183: unable to resolve class Worker.State 
 @ line 183, column 74.
   nds Worker.State> observable, Worker.Sta
                                 ^

/home/mstuart/.config/freeplane/1.6.x/lib/freeplaneGTD/ReportWindow.groovy: 183: unable to resolve class Worker.State 
 @ line 183, column 97.
   vable, Worker.State oldValue, Worker.Sta
                                 ^

13 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:938)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:585)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:534)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:517)
	at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:64)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:43)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:33)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsInDirectory(ScriptCompiler.java:29)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsOnPath(ScriptCompiler.java:21)
	at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:174)
	at org.freeplane.plugin.script.ScriptingRegistration.<init>(ScriptingRegistration.java:140)
	at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:22)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:252)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:268)
	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:185)
	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:84)
	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:386)
	at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)

**Comment by gpapp** [comment]
It's unclear which jdk is installed on your Linux distribution. 

If it's the factory default openjdk, then it's likely that you should install JavaFX. 

```sudo apt-get install openjfx```

**Comment by gpapp** [comment]
Does the error prevent you from using the addon, or is it just a cosmetic issue?

Freeplane tends to throw all kinds of errors when precompiling addon scripts.

**Comment by stuieordie** [comment]
It does prevent the addon from working, when I try running the Next Action script it comes back with script error: null. Also I just ran a sudo apt-get install openjfx and closed/restarted Freeplane and still get these errors:

```
~$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.17.10.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

```

```
at 2018-06-11 20:30:11 CMT,  hash decbd1c234b104b40cb579683e2bedd0
previous report : at 2018-06-11 19:40:47 CMT,  hash 0e415c4cdf88dae38bf5bc5bf7043d68
freeplane_version = 1.6.15; freeplane_xml_version = freeplane 1.6.0
git revision = fe0b3d3c7f05668d40ca1433346f5bec92e26743 Dimitry Polivaev 2018-05-13T15:41:44Z
java_version = 1.8.0_171; os_name = Linux; os_version = 4.13.0-43-generic
error compiling in /home/mstuart/.config/freeplane/1.6.x/lib[ArchiveTask.groovy, DoneMover.groovy, ReviewTask.groovy, ReportModel.groovy, JSHandler.groovy, DateUtil.groovy, Tag.groovy, ReportWindow.groovy, ClipBoardUtil.groovy, GTDMapReader.groovy, MultinodeActionEditor.groovy, ActionEditor.groovy]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during class generation: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.util.logging")

java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.util.logging")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
	at java.lang.ClassLoader$1.run(ClassLoader.java:502)
	at java.lang.ClassLoader$1.run(ClassLoader.java:500)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:355)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:261)
	at org.codehaus.groovy.ast.ClassNode.getUnresolvedSuperClass(ClassNode.java:981)
	at org.codehaus.groovy.ast.ClassNode.getUnresolvedSuperClass(ClassNode.java:976)
	at org.codehaus.groovy.ast.ClassNode.getSuperClass(ClassNode.java:970)
	at org.codehaus.groovy.ast.ClassNode.isDerivedFrom(ClassNode.java:913)
	at org.codehaus.groovy.classgen.asm.InvocationWriter.castToNonPrimitiveIfNecessary(InvocationWriter.java:794)
	at org.codehaus.groovy.classgen.asm.OperandStack.doConvertAndCast(OperandStack.java:344)
	at org.codehaus.groovy.classgen.asm.OperandStack.doGroovyCast(OperandStack.java:279)
	at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.evaluateEqual(BinaryExpressionHelper.java:397)
	at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.eval(BinaryExpressionHelper.java:81)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitBinaryExpression(AsmClassGenerator.java:582)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:49)
	at org.codehaus.groovy.classgen.asm.StatementWriter.writeExpressionStatement(StatementWriter.java:604)
	at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeExpressionStatement(OptimizingStatementWriter.java:354)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitExpressionStatement(AsmClassGenerator.java:564)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:81)
	at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeBlockStatement(OptimizingStatementWriter.java:155)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:510)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:101)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:112)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:374)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:331)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:123)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethod(AsmClassGenerator.java:451)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1063)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:50)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:192)
	at org.codehaus.groovy.control.CompilationUnit$16.call(CompilationUnit.java:805)
	at org.codehaus.groovy.control.CompilationUnit$16.call(CompilationUnit.java:822)
	at org.codehaus.groovy.control.CompilationUnit$16.call(CompilationUnit.java:822)
	at org.codehaus.groovy.control.CompilationUnit$16.call(CompilationUnit.java:822)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1047)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:583)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:561)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:538)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:517)
	at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:64)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:43)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:33)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsInDirectory(ScriptCompiler.java:29)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsOnPath(ScriptCompiler.java:21)
	at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:174)
	at org.freeplane.plugin.script.ScriptingRegistration.<init>(ScriptingRegistration.java:140)
	at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:22)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:252)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:268)
	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:185)
	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:84)
	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:386)
	at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1067)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:583)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:561)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:538)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:517)
	at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:64)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:43)
	at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:33)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsInDirectory(ScriptCompiler.java:29)
	at org.freeplane.plugin.script.ScriptCompiler.compileScriptsOnPath(ScriptCompiler.java:21)
	at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:174)
	at org.freeplane.plugin.script.ScriptingRegistration.<init>(ScriptingRegistration.java:140)
	at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:22)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:252)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:268)
	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:185)
	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:84)
	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:386)
	at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)

```

**Comment by gpapp** [comment]
That's a different kind of problem altogether. What happens there is that the Java security settings used within freeplane prevent the compilation of the addon.

I'm afraid that this issue cannot be resolved by me, but the team packaging freeplane for your Linux distribution. 

For now all I can suggest is is that you install Oracle JDK for Linux openjdk issues.

_Nb: As Oracle is dropping the support of JavaFX, and there are no decent HTML viewer implementations for Java, it is likely that the task list display will be reverted to some standard ui solution._
