### ISSUE TITLE
NullPointerException in  v2.1-alpha-4

### ISSUE THREAD

**Issue by bitclick** [gpapp/FreePlaneGTD#88]
I am using v2.1-alpha-4 in freeplane 1.7.3 on ubuntu 18.04.1 64 bit   running on
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

steps to reproduce using only keyboard shortcuts:
- create new map (ctrl+n)
- do not invoke any freeplanegtd+ functions, do not invoke the "next action list"
- create new node (ins)  empty
- create new subnode (ins) also emtpy
- empty subnode is now selected and has empty parent node
- move subnode to be parents sibling (ctrl+left)

=> error counter in status bar increments 
log output:
```
STDERR: Exception in thread "AWT-EventQueue-1"
STDERR: java.lang.NullPointerException: Cannot invoke method getBooleanProperty() on null object
STDERR: at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
STDERR: at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
STDERR: at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
STDERR: at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
STDERR: at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
STDERR: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
STDERR: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
STDERR: at freeplaneGTD.ReportWindow.refreshContent(ReportWindow.groovy:286)
STDERR: at freeplaneGTD.ReportWindow$refreshContent.call(Unknown Source)
STDERR: at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
STDERR: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
STDERR: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
STDERR: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:82)
STDERR: at freeplaneGTD.GTDMapChangeListener.onNodeMoved(GTDMapChangeListener.groovy:19)
STDERR: at org.freeplane.features.map.MapController.fireNodeMoved(MapController.java:629)
STDERR: at org.freeplane.features.map.mindmapmode.MMapController.moveNodeToWithoutUndo(MMapController.java:806)

```

see attached log file at line 81

[log.0.log](https://github.com/gpapp/FreePlaneGTD/files/2795697/log.0.log)

**Comment by gpapp** [comment]
Please provide sample map, log and steps to reproduce.

**Comment by bitclick** [comment]
yes sorry, i updated the original comment :-)

**Comment by gpapp** [comment]
Fixed in next release
